services:
  db:
    image: "postgres:17.2"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=secret_user
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=shopping_platform
  api:
    image: "shopping-platform:local"
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shopping_platform
      - SPRING_DATASOURCE_USERNAME=secret_user
      - SPRING_DATASOURCE_PASSWORD=secret_password