services:
  db:
    image: "postgres:17.2"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=secret_user
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=shopping_platform